account/urls.py
from django.urls import path
from . import views
app_name = 'account'
urlpatterns = [
    path('home/',views.Home.as_view(), name='home'),
    path('register/', views.registerview.as_view(), name = 'register'),
    path('login/', views.Loginview.as_view(), name = 'login'),
    path('logout/', views.Logoutview.as_view(), name = 'logout'),
    path('details/', views.Detailsview.as_view(), name= 'details1'),
    path('approve/<int:pk>/', views.approve, name= 'approve'),
    path('unapprove/<int:pk>/', views.unapprove, name= 'unapprove'),
    path('delete/<int:pk>/', views.delete, name= 'delete'),
]

online_school/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import redirect_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls', namespace='account')),
    path('',include('teacher.urls', namespace='teacher')),
    path("",redirect_view),
]

teacher/urls.py
from django.urls import path
from . import views
app_name = 'teacher'

urlpatterns = [
    path("add/", views.Addview.as_view(), name='add'),
    path('classroom/',views.Classview.as_view(), name="classroom"),
    path('more/<int:pk>/',views.Dview.as_view(), name="detail"),
]

templates/student/more.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}


<nav class="navbar sticky-top navbar-light bg-light">
          <div class="container-fluid nvbr">
            <div id="main">
              <!-- s<button id="togler" class="openbtn" ></button> -->
              <span class="navbar-toggler-icon" onclick="openNav()"></span>
            </div>
            <a class="navbar-brand wel mx-auto">Class Room</a>
            <div id="mySidebar" class="sidebar">
              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
              <a href="{% url 'account:home'%}">Home</a>
              <a href="{% url 'account:logout' %}">logout</a>
              <a href="#">About us</a>
              <a href="#">complaints</a>
              <a href="#">Settings</a>
                <!-- <a href="#">Contact</a> -->
            </div>
            <ul class="navbar nav">
              <li class="nav-item">
                 <li> <a class="nav-link" href="{% url 'account:home'%}">Home</a></li>
                 <li> <a class="nav-link" href="{% url 'account:logout' %}">Logout</a></li>
                  </li>
                  <li class="nav-item">
                    <div class="dropdown">
                      <button onclick="myFunction()" class="dropbtn"><i class="fa fa-bell fa-2x" aria-hidden="true" style="color: blue;"></i></button>
                      <div id="myDropdown" class="dropdown-content">
                        <a href="{% url 'account:register' %}">Link 1</a>
                        <a href="#">Link 2</a>
                        <a href="#">Link 3</a>
                      </div>
                    </div>
                    </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fa fa-user fa-2x" aria-hidden="true"></i>
                    </a>
                </li>
            </ul>
            
            </div>
          </nav>

        <div class="col-6 mx-auto">
        <div class="card my-4 border-info">
          <div class="card-body">
          <h5 class="card-title">chapter : {{ object.chapter }}</h5>
          {% video object.video '800x600' %}
          <input type="hidden" name="next" value="{{ request.path }}">

          <p class="card-text">notes :{{ object.notes|truncatechars:200 }}</p>
          <a href="{% url 'teacher:classroom' %}" class="btn btn-primary">back to index</a>
        </div>
        </div>
        </div>
  

          <script>
            function openNav() {
              document.getElementById("mySidebar").style.width = "250px";
              document.getElementById("main").style.marginLeft = "0";
              document.getElementById("togler").style.display = "none";
            }
                
                /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
            function closeNav() {
              document.getElementById("mySidebar").style.width = "0";
              document.getElementById("togler").style.marginLeft = "0";
              var x = document.getElementById("togler");
              if (x.style.display === "none") {
              x.style.display="block";
              } else {
              x.style.display = "block";
              }}
              
                    function myFunction() {
                      document.getElementById("myDropdown").classList.toggle("show");
                    }
                    
                    // Close the dropdown menu if the user clicks outside of it
                    window.onclick = function(event) {
                      if (!event.target.matches('.fa-bell')) {
                        var dropdowns = document.getElementsByClassName("dropdown-content");
                        var i;
                        for (i = 0; i < dropdowns.length; i++) {
                          var openDropdown = dropdowns[i];
                          if (openDropdown.classList.contains('show')) {
                            openDropdown.classList.remove('show');
                          }
                        }
                      }
                    }
              </script>
{% endblock content %}

templates/student/student.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<nav class="navbar sticky-top navbar-light bg-light">
          <div class="container-fluid nvbr">
            <div id="main">
              <!-- s<button id="togler" class="openbtn" ></button> -->
              <span class="navbar-toggler-icon" onclick="openNav()"></span>
            </div>
            <a class="navbar-brand wel mx-auto">Class Room</a>
            <div id="mySidebar" class="sidebar">
              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
              <a href="{% url 'account:home'%}">Home</a>
              <a href="{% url 'account:logout' %}">logout</a>
              <a href="#">About us</a>
              <a href="#">complaints</a>
              <a href="#">Settings</a>
                <!-- <a href="#">Contact</a> -->
            </div>
            <ul class="navbar nav">
              <li class="nav-item">
                 <li> <a class="nav-link" href="{% url 'account:home'%}">Home</a></li>
                 <li> <a class="nav-link" href="{% url 'account:logout' %}">Logout</a></li>
                  </li>
                  <li class="nav-item">
                    <div class="dropdown">
                      <button onclick="myFunction()" class="dropbtn"><i class="fa fa-bell fa-2x" aria-hidden="true" style="color: blue;"></i></button>
                      <div id="myDropdown" class="dropdown-content">
                        <a href="{% url 'account:register' %}">Link 1</a>
                        <a href="#">Link 2</a>
                        <a href="#">Link 3</a>
                      </div>
                    </div>
                    </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fa fa-user fa-2x" aria-hidden="true"></i>
                    </a>
                </li>
            </ul>
            
            </div>
          </nav>
        <div class='container mt-5'>
            <div class='row'>
                {% for object in object_list %}
                <div class='col-3'>
                <div class ='card'>
                <div class="card-body">
                <h5 class="card-title">class : {{ object.class1}}</h5>
                <h6 class="card-subtitle mb-2 ">subject: {{object.subject}}</h6>
                <p class="card-text">chapter :{{object.chapter}} </p>
                {% comment %} <p class="card-text">published at :</p> {% endcomment %}
                <a href="{% url 'teacher:detail' object.pk %}" class="btn btn-success">open</a>
                {% comment %} <a href="#" class="card-link">Another link</a> {% endcomment %}
                </div>
                </div>
                </div>
                {% endfor %}
            </div>
        </div>
        


           







          <script>
            function openNav() {
              document.getElementById("mySidebar").style.width = "250px";
              document.getElementById("main").style.marginLeft = "0";
              document.getElementById("togler").style.display = "none";
            }
                
                /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
            function closeNav() {
              document.getElementById("mySidebar").style.width = "0";
              document.getElementById("togler").style.marginLeft = "0";
              var x = document.getElementById("togler");
              if (x.style.display === "none") {
              x.style.display="block";
              } else {
              x.style.display = "block";
              }}
              
                    function myFunction() {
                      document.getElementById("myDropdown").classList.toggle("show");
                    }
                    
                    // Close the dropdown menu if the user clicks outside of it
                    window.onclick = function(event) {
                      if (!event.target.matches('.fa-bell')) {
                        var dropdowns = document.getElementsByClassName("dropdown-content");
                        var i;
                        for (i = 0; i < dropdowns.length; i++) {
                          var openDropdown = dropdowns[i];
                          if (openDropdown.classList.contains('show')) {
                            openDropdown.classList.remove('show');
                          }
                        }
                      }
                    }
              </script>
{% endblock content %}