account/urls.py
from django.urls import path
from . import views
app_name = 'account'
urlpatterns = [
    path('home/',views.Home.as_view(), name='home'),
    path('register/', views.registerview.as_view(), name = 'register'),
    path('login/', views.Loginview.as_view(), name = 'login'),
    path('logout/', views.Logoutview.as_view(), name = 'logout'),
    path('details/', views.Detailsview.as_view(), name= 'details1'),
    path('approve/<int:pk>/', views.approve, name= 'approve'),
    path('unapprove/<int:pk>/', views.unapprove, name= 'unapprove'),
    path('delete/<int:pk>/', views.delete, name= 'delete'),
]

online_school/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import redirect_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls', namespace='account')),
    path('',include('teacher.urls', namespace='teacher')),
    path("",redirect_view),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <title>Home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            {% load static %}
            <link rel="stylesheet" href="{% static 'css/home.css' %}">

      
  </head>
  <body>
 {% if messages %}
  <div class="row">
  <div class="col-sm-12">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3" role="alert">
      {{ message }}
      <button type="button" class="btn-close m-e" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    </div>

  </div>
{% endif %}
    {% block content %}
    
    {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="UTF-8">
        <title>home</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <link rel="stylesheet" href="{% static 'css/caro.css' %}">
    </head>
    <body>
        <nav class="navbar sticky-top navbar-light bg-light">
          <div class="container-fluid nvbr">
            <div id="main">
              <!-- s<button id="togler" class="openbtn" ></button> -->
              <span class="navbar-toggler-icon" onclick="openNav()"></span>
            </div>
            <a class="navbar-brand wel mx-auto" > Welcome to Mysa Learning Center</a>
            <div id="mySidebar" class="sidebar">
              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
              <a href="{% url 'account:register' %}">Register</a>
              <a href="{% url 'account:login' %}">Login</a>
              <a href="#">About us</a>
              <a href="#">complaints</a>
              <a href="#">Settings</a>
              <a href="#">Log out</a>
                <!-- <a href="#">Contact</a> -->
            </div>
            <ul class="navbar nav">
              <li class="nav-item">
                 <li> <a class="nav-link" href="{% url 'account:register' %}">Register</a></li>
                 <li> <a class="nav-link" href="{% url 'account:login' %}">Login</a></li>
                  </li>
                  <li class="nav-item">
                    <div class="dropdown">
                      <button onclick="myFunction()" class="dropbtn"><i class="fa fa-bell fa-2x" aria-hidden="true" style="color: blue;"></i></button>
                      <div id="myDropdown" class="dropdown-content">
                        <a href="{% url 'account:register' %}">Link 1</a>
                        <a href="#">Link 2</a>
                        <a href="#">Link 3</a>
                      </div>
                    </div>
                    </li>
                  {% comment %} <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fa fa-user fa-2x" aria-hidden="true"></i>
                    </a>
                </li> {% endcomment %}
            </ul>
            
            </div>
          </nav>
          <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <ol class="carousel-indicators">
          <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
          <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
          <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
          <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'images/scene5.jpg' %}" class="d-block w-100 image-fluid" alt="..." >
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/scene6.jpg' %}" class="d-block w-100 image-fluid" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/scene7.jpg' %}"class="d-block w-100 image-fluid" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/scene8.jpg' %}"class="d-block w-100 image-fluid" alt="...">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </a>

      </div><hr><br>

            
      <script>
            function openNav() {
              document.getElementById("mySidebar").style.width = "250px";
              document.getElementById("main").style.marginLeft = "0";
              document.getElementById("togler").style.display = "none";
            }
                
                /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
            function closeNav() {
              document.getElementById("mySidebar").style.width = "0";
              document.getElementById("togler").style.marginLeft = "0";
              var x = document.getElementById("togler");
              if (x.style.display === "none") {
              x.style.display="block";
              } else {
              x.style.display = "block";
              }}
              
                    function myFunction() {
                      document.getElementById("myDropdown").classList.toggle("show");
                    }
                    
                    // Close the dropdown menu if the user clicks outside of it
                    window.onclick = function(event) {
                      if (!event.target.matches('.fa-bell')) {
                        var dropdowns = document.getElementsByClassName("dropdown-content");
                        var i;
                        for (i = 0; i < dropdowns.length; i++) {
                          var openDropdown = dropdowns[i];
                          if (openDropdown.classList.contains('show')) {
                            openDropdown.classList.remove('show');
                          }
                        }
                      }
                    }
              </script>
      
      </body>
      </html>